# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [119]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [120]:
# your code here
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [121]:
# Method 1
n_d_array = np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]], [[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]])
a = n_d_array
print(a.shape)

(2, 3, 5)


In [122]:
# Method 2
z=np.zeros((2,3,5))
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [123]:
# Method 3
y =np.arange(30).reshape(2,3,5)
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### 4. Print *a*.


In [124]:
# your code here
a

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [125]:
# your code here
b = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]] , [[1,2,3],[1,2,3]], [[1,2,3],[1,2,3]] ,[[1,2,3],[1,2,3]]])
print(b.shape)
b.fill(1)

(5, 2, 3)


#### 6. Print *b*.


In [126]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [127]:
# your code here
print(a.size)
print(b.size)

#Yes, they have the same size.

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [128]:
# No se puede añadir la matriz a "a" la "b", ya que tienen distinta dimensión, por lo que su suma no sería posible.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [129]:
# your code here
c = b.reshape(2,3,5)
print(c.shape)
c

(2, 3, 5)


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [130]:
# your code/answer here
d = a + c
d

#Funciona porque tienen la misma dimensión 



array([[[2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6]],

       [[2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [131]:
# your code/answer here
print(a)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [132]:
print(d)

[[[2 3 4 5 6]
  [2 3 4 5 6]
  [2 3 4 5 6]]

 [[2 3 4 5 6]
  [2 3 4 5 6]
  [2 3 4 5 6]]]


In [133]:
#Al haber sumado una matriz de unos, lo que ha hecho ha sido sacar una nueva matriz sumando uno a cada elemento de sus dos dimensiones.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [134]:
# your code here
e = a * c
e

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [135]:
# "e" y "a" son iguales, ya que, al ser c una matriz de unos, multiplica cada elemento por uno, por lo que la función es la misma.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [136]:
# your code here
max_ = d.max()
min_ = d.min()
mean = d.mean()
print(max_)
print(min_)
print(mean)

6
2
4.0


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [137]:
# your code here
f = np.empty([2, 3, 5], int)
f

array([[[   0, 2043,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]],

       [[   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [141]:
# your code here
f = []
for i in np.nditer(d):
    if i > min_ and i < mean:
        f.append(25)
    elif i > mean and i < max_:
        f.append(75)
    elif i == mean:
        f.append(50)
    elif i == min_:
        f.append(0)
    elif i == max_:
        f.append(100)
    
f = np.reshape(f,(2,3,5))

print(f)

[[[  0  25  50  75 100]
  [  0  25  50  75 100]
  [  0  25  50  75 100]]

 [[  0  25  50  75 100]
  [  0  25  50  75 100]
  [  0  25  50  75 100]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [142]:
# your code here
print(d)

print(f)

[[[2 3 4 5 6]
  [2 3 4 5 6]
  [2 3 4 5 6]]

 [[2 3 4 5 6]
  [2 3 4 5 6]
  [2 3 4 5 6]]]
[[[  0  25  50  75 100]
  [  0  25  50  75 100]
  [  0  25  50  75 100]]

 [[  0  25  50  75 100]
  [  0  25  50  75 100]
  [  0  25  50  75 100]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here